# Generated by Django 5.2 on 2026-03-28 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ai_response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sentiment',
            field=models.CharField(blank=True, choices=[('POS', 'Positive'), ('NEG', 'Negative'), ('NEU', 'Neutral')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='urgency',
            field=models.CharField(blank=True, choices=[('H', 'High'), ('M', 'Medium'), ('L', 'Low')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='author_email',
            field=models.EmailField(max_length=100),
        ),
    ]
