# Generated by Django 5.2 on 2026-03-28 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_ticket_ai_response_ticket_category_ticket_sentiment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('N', 'New'), ('D', 'Done'), ('P', 'In Progress'), ('R', 'Rejected')], default='N', max_length=1),
        ),
    ]
